name: Build QMK firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:

    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
        submodules: recursive

    - name: Checkout userspace
      uses: actions/checkout@v3
      with:
        path: keyboards/sofle/keymaps/${{ github.actor }}

    - name: Build firmware
      run: qmk compile -c -e CONVERT_TO=liatris -kb sofle -km "${{ github.actor }}"

    - name: Build json
      run:  qmk c2json -kb sofle -km "${{ github.actor }}" -o sofle-${{ github.actor }}.json

    - name: Archive firmware
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: sofle-${{ github.actor }}-firmware
        path: |
          *.uf2
          
    - name: Archive json
      uses: actions/upload-artifact@v4
      with:
        name: sofle-${{ github.actor }}-json
        path: |
          sofle-${{ github.actor }}.json